//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsistensiMedisDatabase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatabaseMedAssistEntities : DbContext
    {
        public DatabaseMedAssistEntities()
            : base("name=DatabaseMedAssistEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DatabaseAmbulance> DatabaseAmbulances { get; set; }
        public virtual DbSet<DatabaseDoctor> DatabaseDoctors { get; set; }
        public virtual DbSet<DatabaseMedicine> DatabaseMedicines { get; set; }
        public virtual DbSet<DatabasePharmacyStock> DatabasePharmacyStocks { get; set; }
        public virtual DbSet<DatabaseRequest> DatabaseRequests { get; set; }
        public virtual DbSet<DatabaseVoucher> DatabaseVouchers { get; set; }
        public virtual DbSet<DatabaseUser> DatabaseUsers { get; set; }
    }
}
