//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsistensiMedisDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatabaseRequest
    {
        public int ID { get; set; }
        public Nullable<bool> IsLocked { get; set; }
        public Nullable<System.Guid> SenderID { get; set; }
        public Nullable<System.Guid> ReceiverID { get; set; }
        public Nullable<float> LocationLatitude { get; set; }
        public Nullable<float> LocationLongitude { get; set; }
        public string LocationDetail { get; set; }
        public string Request { get; set; }
        public string RequestDetail { get; set; }
    }
}
