//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsistensiMedisDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatabaseVoucher
    {
        public int Id { get; set; }
        public Nullable<System.Guid> VoucherID { get; set; }
        public Nullable<decimal> Nominal { get; set; }
    }
}
