//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsistensiMedisDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatabaseDoctor
    {
        public int DoctorNumber { get; set; }
        public string DoctorName { get; set; }
        public string DoctorHospital { get; set; }
        public Nullable<int> DoctorAge { get; set; }
        public byte[] DoctorPicture { get; set; }
        public string DoctorType { get; set; }
        public Nullable<System.Guid> DoctorID { get; set; }
        public bool AppointmentMonday { get; set; }
        public bool AppointmentTuesday { get; set; }
        public bool AppointmentWednesday { get; set; }
        public bool AppointmentThursday { get; set; }
        public bool AppointmentFriday { get; set; }
        public bool AppointmentSaturday { get; set; }
        public bool AppointmentSunday { get; set; }
        public Nullable<float> HospitalLatitude { get; set; }
        public Nullable<float> HospitalLongitude { get; set; }
    }
}
