//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsistensiMedisDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatabaseUser
    {
        public int UserNumber { get; set; }
        public string Nama { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public byte[] FotoProfil { get; set; }
        public Nullable<System.Guid> UserID { get; set; }
        public string Alamat { get; set; }
        public string TempatLahir { get; set; }
        public Nullable<System.DateTime> TanggalLahir { get; set; }
        public Nullable<long> NomorTelepon { get; set; }
        public string TipeUser { get; set; }
        public Nullable<float> LatitudeUser { get; set; }
        public Nullable<float> LongitudeUser { get; set; }
        public Nullable<decimal> SaldoUser { get; set; }
    }
}
